# LangChain Generative AI Series — Understanding Embeddings

## Embeddings
Embeddings are numerical vector representations of text (words, sentences, or documents) 
that capture **semantic meaning**.  

They help AI models understand *similarity* between texts based on meaning, not just keywords.  

Example:
- “AI revolution” and “machine learning boom” → similar embeddings  
- “AI revolution” and “coffee recipe” → very different embeddings


### Dimension
Each embedding is a vector of numbers — the **length of that vector is called its dimension**.  

- Example: a 384-dimensional embedding → `[0.12, -0.44, 0.03, ..., 0.87]` (384 values)  
- Higher dimensions capture more nuance, but increase storage and computation cost.

**Analogy:**  
Think of “dimension” like how many features you use to describe something.  
More dimensions = more detail.



### Environment Setup for Embeddings Notebook

- Before running the Embeddings notebook, make sure your environment is properly configured for using Hugging Face and Ollama embeddings.

### Setup Hugging Face Access Token

- Some Hugging Face models (like sentence-transformers, e5, or bge) require authentication through a free Hugging Face access token.

Steps:

1. Go to https://huggingface.co/settings/tokens

2. Click “New Token” → Choose read permission.

3. Copy the generated token.

4. Set it in your environment:


### Setting Up Ollama for Local Embeddings

- Ollama allows you to generate embeddings locally using open-source models.
- No internet calls, no API costs, and full data privacy.

- Steps to Install & Use:

1. Install Ollama → https://ollama.com/download

- (Choose installer for your OS: Windows, macOS, or Linux)

2. Verify installation

- ollama --version


3. Pull an embedding model

- ollama pull mxbai-embed-large (or)

- ollama pull nomic-embed-text

#### Play with different embedding models present in both Ollama and HuggingFace

# HuggingFaceEmbeddings

In [9]:
## The below statements load all your enivronment variables which are stored in .env file.
import os
from dotenv import load_dotenv
load_dotenv()


os.environ["HF_TOKEN"]=os.getenv("HF_TOKEN")

python-dotenv could not parse statement starting at line 16


In [19]:
import warnings 
warnings.filterwarnings('ignore')
from langchain.embeddings import HuggingFaceEmbeddings

hf_embed = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
text = "Artificial Intelligence enables automation and innovation."
vector = hf_embed.embed_query(text)
print("Model: all-MiniLM-L6-v2 | Dimension:", len(vector))
print(vector)


Model: all-MiniLM-L6-v2 | Dimension: 384
[0.006710764020681381, -0.03021145984530449, 0.03612774610519409, -0.024205058813095093, 0.03632498160004616, 0.0052694776095449924, -0.011544600129127502, 0.02457614429295063, 0.009152376092970371, 0.022662177681922913, -0.012599806301295757, 0.01336205005645752, 0.015274151228368282, -0.005008374806493521, 0.014012772589921951, 0.016316108405590057, -0.027812516316771507, -0.09641152620315552, -0.09179233759641647, -0.1181873083114624, 0.035035256296396255, 0.01351203117519617, -0.01564280316233635, -0.015023092739284039, -0.0033331706654280424, 0.0553186871111393, -0.0010326438350602984, -0.013327238149940968, -0.0048011839389801025, -0.032486140727996826, -0.018555577844381332, 0.027148326858878136, 0.0907001942396164, 0.014507433399558067, -0.020198224112391472, -0.01283977273851633, -0.005653226748108864, 0.07879038155078888, 0.08629973977804184, -0.09303900599479675, -0.00010246636520605534, -0.12210386991500854, 0.014855635352432728, 0.0

In [16]:
hf_embed = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
vector = hf_embed.embed_query(text)
print("Model: all-mpnet-base-v2 | Dimension:", len(vector))
print(vector)

Model: all-mpnet-base-v2 | Dimension: 768
[-0.04543709382414818, 0.07388098537921906, -0.08444563299417496, 0.008747895248234272, -0.039932336658239365, 0.004490540828555822, 0.025254709646105766, 0.025367848575115204, -0.005588780157268047, -0.01880740188062191, 0.07129602879285812, 0.16159896552562714, -0.06148507818579674, 0.11587779223918915, 0.04435080662369728, 0.04077485203742981, 0.005166409071534872, -0.01582944765686989, -0.01269922312349081, 0.02506767213344574, -0.03780914098024368, -0.015550071373581886, -0.013911852613091469, 0.0013428401434794068, -0.023488957434892654, 0.056424256414175034, 0.03240064159035683, -0.010711210779845715, 0.04896720498800278, -0.031160902231931686, -0.026928968727588654, 0.00492405379191041, 0.04498153552412987, 0.04104003682732582, 1.4647189345851075e-06, -0.04853547737002373, 0.033312052488327026, 0.025724273175001144, -0.0641857385635376, -0.029656317085027695, 0.019649220630526543, 0.05159533768892288, -0.002325269393622875, 0.0113709354

In [20]:
hf_embed = HuggingFaceEmbeddings(model_name="BAAI/bge-base-en")
vector = hf_embed.embed_query(text)
print("Model: BGE Base | Dimension:", len(vector))


Model: BGE Base | Dimension: 768


In [21]:
hf_embed = HuggingFaceEmbeddings(model_name="intfloat/e5-base-v2")
vector = hf_embed.embed_query(text)
print("Model: E5 Base | Dimension:", len(vector))


Model: E5 Base | Dimension: 768


# OllamaEmbeddings

In [ ]:
from langchain_community.embeddings import OllamaEmbeddings

ollama_embed = OllamaEmbeddings(model="nomic-embed-text:latest")
vector = ollama_embed.embed_query("Local embeddings are privacy-friendly.")
print("Model: nomic-embed-text:latest | Dimension:", len(vector))


Model: mxbai-embed-large | Dimension: 768


In [24]:
from langchain_community.embeddings import OllamaEmbeddings

ollama_embed = OllamaEmbeddings(model="mxbai-embed-large")
vector = ollama_embed.embed_query("Generative AI is the one of the fast booming field")
print("Model: mxbai-embed-large | Dimension:", len(vector))


Model: mxbai-embed-large | Dimension: 1024


# Comparing Similaritities

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
hf_embed = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

words = ["AI", "machine", "learning", "coffee"]
word_vectors = [hf_embed.embed_query(word) for word in words]

# Compare similarity
similarity_matrix = cosine_similarity(word_vectors)
print("Word Similarity Matrix:\n", np.round(similarity_matrix, 3))

"""Words like “AI” and “machine” should show higher similarity than “AI” and “coffee.”"""

Word Similarity Matrix:
 [[1.    0.525 0.549 0.277]
 [0.525 1.    0.386 0.417]
 [0.549 0.386 1.    0.317]
 [0.277 0.417 0.317 1.   ]]


In [ ]:
sentences = [
    "Artificial Intelligence is transforming industries.",
    "Machine Learning is a subset of AI.",
    "I love drinking coffee in the morning."
]

sentence_vectors = [hf_embed.embed_query(sentence) for sentence in sentences]
similarity = cosine_similarity(sentence_vectors)
print("Sentence Similarity Matrix:\n", np.round(similarity, 3))

"""Sentence 1 and 2 are having higher similarity (same topic)

Sentence 3 is has very low similarity"""


Sentence Similarity Matrix:
 [[1.    0.523 0.053]
 [0.523 1.    0.078]
 [0.053 0.078 1.   ]]


## Using Paid Embedding Models (OpenAI, Google, Cohere, etc.)

- While open-source models like Hugging Face and Ollama are completely free to use,
- some embedding providers (like OpenAI, Google, Cohere, and VoyageAI) require API keys and paid credits for usage.

#### OpenAIEmbeddings

In [ ]:
from langchain.embeddings import OpenAIEmbeddings
import os

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

openai_embed = OpenAIEmbeddings(model="text-embedding-3-small")
vector = openai_embed.embed_query("Artificial Intelligence is transforming industries.")
print("OpenAI Embedding Dimension:", len(vector))



#### GoogleGenerativeAIEmbeddings

In [ ]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import os

os.environ["GOOGLE_API_KEY"] = "your_google_api_key_here"

google_embed = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
vector = google_embed.embed_query("Generative AI enables contextual understanding.")
print("Google Embedding Dimension:", len(vector))


#### Cohere Embeddings

In [ ]:
from langchain.embeddings import CohereEmbeddings
import os

os.environ["COHERE_API_KEY"] = "your_cohere_api_key_here"

cohere_embed = CohereEmbeddings(model="embed-english-light-v3.0")
vector = cohere_embed.embed_query("Cohere embeddings support multilingual contexts.")
print("Cohere Embedding Dimension:", len(vector))


#### Embeddings convert text into numerical vectors capturing meaning.
#### Similar texts have closer embeddings in vector space.
#### LangChain supports multiple embedding models:
   - OpenAI
   - HuggingFace
   - Google Generative AI
   - Cohere, Mistral, Instructor,NVIDIA, IBM watsonx, AWS, Google Vertex, etc.
#### Embeddings form the backbone of RAG pipelines and semantic search.




### Next in this Series:
**“Prompt Templates in LangChain — Structuring Dynamic Interactions with LLMs”**

Stay tuned for the next notebook where we’ll explore:
- What prompt templates are  
- Why they’re essential for consistent LLM responses  
- How to build reusable, dynamic prompt components in LangChain  

Explore the complete series here:  
[LangChain-Generative-AI-Series](https://github.com/Mouli423/LangChain-Generative-AI-Series)

#LangChain #GenerativeAI #MachineLearning #AIEngineering #PromptEngineering #LLM
